toolchain: also disable libstdc++.la when disabling the .so
libtool finds the .la and looks for the .so because it appears on the
"library_names" line. Instead of fixing the file, simply disabling the
.la is enough to fix the problem.

diff --git a/toolchain b/toolchain
--- a/toolchain
+++ b/toolchain
@@ -912,11 +912,16 @@ tc_finish() {
 		fi
 
 		# If we have libstdc++.so, it likely depends on libgcc_s.so, so we'll rename it
-		# too so that we only keep libstdc++.a
+		# too so that we only keep libstdc++.a. Note that we must also remove the .la
+		# otherwise some libtool-based builds will fail.
 
 		if [ -e "$TC_DST/$PREF/$PREF"/sys-root/lib/libstdc++.so ]; then
 			echo "Disabling shared libstdc++ for toolchain $PREF (libstdc++.so) ..."
 			mv "$TC_DST/$PREF/$PREF"/sys-root/lib/{,.unused.}libstdc++.so || die $?
+			if [ -e "$TC_DST/$PREF/$PREF"/sys-root/lib/libstdc++.la ]; then
+				echo "  (Disabling libstdc++.la as well) ..."
+				mv "$TC_DST/$PREF/$PREF"/sys-root/lib/{,.unused.}libstdc++.la || die $?
+			fi
 		fi
 	done
 	cd "$p" || $?
